name = "catppuccin-mocha"

[border]
r = 88
g = 91
b = 112

[title]
r = 137
g = 180
b = 250

[text]
r = 205
g = 214
b = 244

[green]
r = 166
g = 227
b = 161

[yellow]
r = 249
g = 226
b = 175

[red]
r = 243
g = 139
b = 168

[cyan]
r = 137
g = 220
b = 235

[purple]
r = 203
g = 166
b = 247

[orange]
r = 250
g = 179
b = 135

[teal]
r = 148
g = 226
b = 213
